splits: 3
np_dir: Nanopore
fastq: fastq
extension: pod5
sample: SampleName
study: StudyName
webin_user: Username
webin_pass: SuperSecretPassword
key: Path/To/ENA/keyfile.tsv
instrument_model: PromethION
library_name: LIB-
library_source: METAGENOMIC
library_selection: RANDOM
library_strategy: WGS
library_layout: SINGLE
